#plugins:
#  - prettier-plugin-java
tabWidth: 4
useTabs: false
bracketSpacing: true
bracketSameLine: false
printWidth: 125
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: all
arrowParens: avoid